### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [tessmero/tc359_project11_tessmero#1]
Looks very good for the most part, but there are a few items I'd like you to fix:
- When not logged in, I still see a link to create a new story
- When not logged in and on a Show page, I still see a link to edit a story
- When not logged in, I don't see a link to the Show page, even though I'm allowed to access it

**Comment by tessmero** [comment]
Fixed this problem: When not logged in, I still see a link to create a new story

Are you sure you were looking at the right project? My website is a database of movies, not stories.

I was not able to replicate the other problems:
When not logged in and on a Show page, I still see a link to edit a story
When not logged in, I don't see a link to the Show page, even though I'm allowed to access it

**Comment by chrisvfritz** [comment]
The stories instead of movies is my fault. I was looking at the correct app, but I had probably just looked at another app with stories and was still in story mode for some reason, when I was giving your feedback. Sorry about the confusion!

I see the fix on GitHub, but did you also push to Heroku? I'm still seeing the issue there. 

As for the other two problems, I still see them:
- On the show page, [a link to edit a story is _always_ displayed here](https://github.com/tessmero/tc359_project11_tessmero/blob/master/app/views/movies/show.html.erb#L23), even if a user is not signed in
- When a user is not signed in, [this link](https://github.com/tessmero/tc359_project11_tessmero/blob/master/app/views/movies/index.html.erb#L25) is never displayed, even though anonymous visitors _do_ have access to that action

Let me know if that helps!

**Comment by tessmero** [comment]
Fixed now. than you that was very helpful

**Comment by tessmero** [comment]
Now on heroku, the url is different now - I edited my project showcase to reflect this.

**Comment by chrisvfritz** [comment]
:+1: Looks fantastic!
